kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs:12
  SourceLocation: https://github.com/openshift/nodejs-ex
  Ref: HEAD
  SourceType: git
  Ports:
  - 8080/TCP
  Application: nodejs-app
  Project: project4
  Name: nodejs-frontend
  Storage:
  - Name: nodejs-storage
    Size: 1Gi
    Path: /data
  Url:
  - Name: odo-nodejs
    Port: 8080
